#' Population Density Mexico HDX data 2022
#'
#' A subset of data from the HUMANITARIAN DATA EXCHANGE Population Density of Mexico
#' dataset ...
#'
#' @format ## `hdx_pop2022`
#' A sf & data frame with 463830 rows and 3 columns:
#' \describe{
#'   \item{h3}{id of hexagon}
#'   \item{popolation}{Population Density for 400m H3 Hexagons}
#'   \item{geom}{geometry}
#'   ...
#' }
#' @source <https://data.humdata.org/dataset/kontur-population-mexico?>
"hdx_pop2022"

#' Population Density Mexico HDX data 2023
#'
#' A subset of data from the HUMANITARIAN DATA EXCHANGE Population Density of Mexico
#' dataset ...
#'
#' @format ## `hdx_pop2023`
#' A sf & data frame with 456514 rows and 3 columns:
#' \describe{
#'   \item{h3}{id of hexagon}
#'   \item{popolation}{Population Density for 400m H3 Hexagons}
#'   \item{geom}{geometry}
#'   ...
#' }
#' @details
#' EPSG 4326...
#'
#' @source <https://data.humdata.org/dataset/kontur-population-mexico?>
"hdx_pop2023"

#' Population Density Mexico HDX data 2021
#'
#' A subset of data from the HUMANITARIAN DATA EXCHANGE Population Density of Mexico
#' dataset ...
#'
#' @format ## `hdx_pop2021`
#' A sf & data frame with 362028 rows and 2 columns:
#' \describe{
#'   \item{popolation}{Population Density for 400m H3 Hexagons}
#'   \item{geom}{geometry}
#'   ...
#' }
#' @details
#' EPSG 4326...
#'
#' @source <https://data.humdata.org/dataset/kontur-population-dataset>
"hdx_pop2021"


#' population by municipality /(ITER 2020/)
#'
#' A subset of data from the HUMANITARIAN DATA EXCHANGE Population Density of Mexico
#' dataset ...
#'
#' @format ## `pop2020`
#' A data frame with 2469 rows and 44 columns:
#' \describe{
#'   \item{CVEGEO}{id of the municipality.}
#'   \item{pobtot}{population}
#'   \item{pobfem}{female population}
#'   \item{pobmas}{male population}
#'   \item{p_0a2}{population between 0 and 2 years of age}
#'   \item{p_0a2_f}{female population between 0 and 2 years of age}
#'   \item{p_0a2_m}{male population between 0 and 2 years of age}
#'   \item{p_3ymas}{population over 3 years of age}
#'   \item{p_3ymas_f}{female population over 3 years of age}
#'   \item{p_3ymas_m}{male population over 3 years of age}
#'   \item{p_5ymas}{population over 5 years of age}
#'   \item{p_5ymas_f}{female population over 5 years of age}
#'   \item{p_5ymas_m}{male population over 5 years of age}
#'   \item{p_12ymas}{population over 12 years of age}
#'   \item{p_12ymas_f}{female population over 12 years of age}
#'   \item{p_12ymas_m}{male population over 12 years of age}
#'   \item{p_15ymas}{population over 15 years of age}
#'   \item{p_15ymas_f}{female population over 15 years of age}
#'   \item{p_15ymas_m}{male population over 15 years of age}
#'   \item{p_18ymas}{population over 18 years of age}
#'   \item{p_18ymas_f}{female population over 18 years of age}
#'   \item{p_18ymas_m}{male population over 18 years of age}
#'   \item{p_3a5}{population between 3 and 5 years of age}
#'   \item{p_3a5_f}{female population between 3 and 5 years of age}
#'   \item{p_3a5_m}{male population between 3 and 5 years of age}
#'   \item{p_6a11}{population between 6 and 11 years of age}
#'   \item{p_6a11_f}{female population between 6 and 11 years of age}
#'   \item{p_6a11_m}{male population between 6 and 11 years of age}
#'   \item{p_8a14}{population between 8 and 14 years of age}
#'   \item{p_8a14_f}{female population between 8 and 14 years of age}
#'   \item{p_8a14_m}{male population between 8 and 14 years of age}
#'   \item{p_12a14}{population between 12 and 14 years of age}
#'   \item{p_12a14_f}{female population between 12 and 14 years of age}
#'   \item{p_12a14_m}{male population between 12 and 14 years of age}
#'   \item{p_15a17}{population between 15 and 17 years of age}
#'   \item{p_15a17_f}{female population between 15 and 17 years of age}
#'   \item{p_15a17_m}{male population between 15 and 17 years of age}
#'   \item{p_18a24}{population between 18 and 24 years of age}
#'   \item{p_18a24_f}{female population between 18 and 24 years of age}
#'   \item{p_18a24_m}{male population between 18 and 24 years of age}
#'   \item{p_15a49_f}{female population between 15 and 49 years of age}
#'   \item{p_60ymas}{population over 60 years of age}
#'   \item{p_60ymas_f}{female population over 60 years of age}
#'   \item{p_60ymas_m}{male population over 60 years of age}
#'   ...
#' }
#' @details
#' The population data by total number and sex for each municipality were obtained from the dataset of territorial indicators known as ITER /(Indicadores Territoriales/), which is a database derived from the 2020 Population and Housing Census generated by Instituto Nacional de Estadística y Geografía (INEGI)
#'
#' @source <https://www.inegi.org.mx/app/scitel/Default?ev=9>
"pop2020"
